bpm = 69
steps = 16
swing = 0
repeat = true

[[tracks]]
name = "Kick"
sample = "samples/kits/harsh 909/Kick Short.wav"
mute = false
solo = false
gain_db = 3.0

[tracks.delay]
on = false
time = "1/4"
feedback = 0.3499999940395355
mix = 0.25

[tracks.pattern]
Visual = "x...x...x...x..."

[[tracks]]
name = "Snare"
sample = "samples/kits/harsh 909/Snare.wav"
mute = true
solo = false
gain_db = 0.0

[tracks.delay]
on = true
time = "1/4"
feedback = 0.3499999940395355
mix = 0.25

[tracks.pattern]
Visual = "x"

[[tracks]]
name = "Clap"
sample = "samples/kits/harsh 909/Clap.wav"
mute = false
solo = false
gain_db = -2.0

[tracks.delay]
on = false
time = "1/8"
feedback = 0.25
mix = 0.20000000298023224

[tracks.pattern]
Visual = "..x. ..x. ..x. ..x."

[[tracks]]
name = "Hat"
sample = "samples/kits/harsh 909/Closed Hat.wav"
mute = false
solo = false
gain_db = -6.0

[tracks.delay]
on = false
time = "1/8"
feedback = 0.20000000298023224
mix = 0.15000000596046448

[tracks.pattern]
Visual = "xx.x"

[[tracks]]
name = "Rim"
sample = "samples/kits/harsh 909/Rim.wav"
mute = true
solo = false
gain_db = -3.0

[tracks.delay]
on = false
time = "1/8"
feedback = 0.20000000298023224
mix = 0.15000000596046448

[tracks.pattern]
Visual = ".... .... x... ...."
